name: Test and build
on:
  pull_request: {}
  push: {branches: [master]}
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - UnityProject/SpicyShower
        unityVersion:
          - 2019.3.7f1
        testMode:
          - playmode
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
    
      - name: Cache library
        uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-

      - name: Run tests
        id: runTests
        uses: webbertakken/unity-test-runner@v1.3
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          testMode: ${{ matrix.testMode }}
          artifactsPath: test-results

      - name: Actifact test results
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: Test results
          path: ${{ steps.runTests.outputs.artifactsPath }}

  build:
    name: Build
    needs: test
    if: github.ref == 'ref/head/master' || github.base_ref == 'ref/head/master'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - UnityProject/SpicyShower
        unityVersion:
          - 2019.3.7f1
        targetPlatform:
          - StandaloneWindows
          - StandaloneWindows64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
    
      - name: Cache library
        uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-

      - name: Build game
        uses: webbertakken/unity-builder@v0.11
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildsPath: build

      - name: Artifact build
        uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
